"""add palette_colors

Revision ID: f706a70b2ee1
Revises: 04031c06189e
Create Date: 2026-06-01 13:10:17.950894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f706a70b2ee1'
down_revision: Union[str, Sequence[str], None] = '04031c06189e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('palette_colors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'palette_colors')
    # ### end Alembic commands ###
